import { pgTable, text, integer, boolean, varchar, jsonb, timestamp } from "drizzle-orm/pg-core";

// ============================================================
// Questions, Quizzes, Quiz Results, Attempts, Skill Progress
// ============================================================

export const questions = pgTable("questions", {
  id: text("id").primaryKey(),
  text: text("text").default(""),
  options: text("options").array().default([]),
  correctOptionIndex: integer("correct_option_index").default(0),
  explanation: text("explanation").default(""),
  videoUrl: text("video_url").default(""),
  imageUrl: text("image_url").default(""),
  skillIds: text("skill_ids").array().default([]),
  pathId: text("path_id"),
  subject: text("subject").notNull(),
  sectionId: text("section_id"),
  difficulty: varchar("difficulty", { length: 20 }).default("Medium"),
  type: varchar("type", { length: 20 }).default("mcq"),
  // Content workflow
  ownerType: varchar("owner_type", { length: 20 }).default("platform"),
  ownerId: text("owner_id").default(""),
  createdBy: text("created_by").default(""),
  assignedTeacherId: text("assigned_teacher_id").default(""),
  approvalStatus: varchar("approval_status", { length: 20 }).default("draft"),
  approvedBy: text("approved_by").default(""),
  approvedAt: integer("approved_at"),
  reviewerNotes: text("reviewer_notes").default(""),
  revenueSharePercentage: integer("revenue_share_percentage"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const quizzes = pgTable("quizzes", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description").default(""),
  pathId: text("path_id").notNull(),
  subjectId: text("subject_id").notNull(),
  sectionId: text("section_id"),
  type: varchar("type", { length: 20 }).default("quiz"),
  mode: varchar("mode", { length: 20 }).default("regular"),
  settings: jsonb("settings").default({ showExplanations: true, showAnswers: true, maxAttempts: 3, passingScore: 60, timeLimit: 60 }),
  accessType: varchar("access_type", { length: 20 }).default("free"),
  accessPrice: integer("access_price").default(0),
  accessAllowedGroupIds: text("access_allowed_group_ids").array().default([]),
  questionIds: text("question_ids").array().default([]),
  skillIds: text("skill_ids").array().default([]),
  targetGroupIds: text("target_group_ids").array().default([]),
  targetUserIds: text("target_user_ids").array().default([]),
  dueDate: text("due_date"),
  isPublished: boolean("is_published").default(false),
  showOnPlatform: boolean("show_on_platform").default(true),
  // Content workflow
  ownerType: varchar("owner_type", { length: 20 }).default("platform"),
  ownerId: text("owner_id").default(""),
  createdBy: text("created_by").default(""),
  assignedTeacherId: text("assigned_teacher_id").default(""),
  approvalStatus: varchar("approval_status", { length: 20 }).default("draft"),
  approvedBy: text("approved_by").default(""),
  approvedAt: integer("approved_at"),
  reviewerNotes: text("reviewer_notes").default(""),
  revenueSharePercentage: integer("revenue_share_percentage"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const quizResults = pgTable("quiz_results", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  quizId: text("quiz_id").notNull(),
  quizTitle: text("quiz_title").notNull(),
  score: integer("score").default(0),
  totalQuestions: integer("total_questions").default(0),
  correctAnswers: integer("correct_answers").default(0),
  wrongAnswers: integer("wrong_answers").default(0),
  unanswered: integer("unanswered").default(0),
  timeSpent: text("time_spent").default(""),
  date: text("date").default(""),
  skillsAnalysis: jsonb("skills_analysis").default([]),
  questionReview: jsonb("question_review").default([]),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const questionAttempts = pgTable("question_attempts", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  questionId: text("question_id").notNull(),
  selectedOptionIndex: integer("selected_option_index").default(-1),
  isCorrect: boolean("is_correct").default(false),
  timeSpentSeconds: integer("time_spent_seconds").default(0),
  date: text("date").default(""),
  pathId: text("path_id").default(""),
  subjectId: text("subject_id").default(""),
  sectionId: text("section_id").default(""),
  skillIds: text("skill_ids").array().default([]),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const skillProgress = pgTable("skill_progress", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  skillId: text("skill_id").notNull(),
  skill: text("skill").default(""),
  pathId: text("path_id").default(""),
  subjectId: text("subject_id").default(""),
  sectionId: text("section_id").default(""),
  mastery: integer("mastery").default(0),
  status: varchar("status", { length: 20 }).default("weak"),
  attempts: integer("attempts").default(0),
  lastQuizId: text("last_quiz_id").default(""),
  lastQuizTitle: text("last_quiz_title").default(""),
  lastAttemptAt: timestamp("last_attempt_at").defaultNow(),
  recommendedAction: text("recommended_action").default(""),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
